version: '3.8'
services:
  db:
    image: mysql:8
    container_name: carp-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: patil
      MYSQL_DATABASE: carp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
